# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Collapsable_Expandable_Classes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'PageMenu'
  # Pods for Collapsable_Expandable_Classes

  target 'Collapsable_Expandable_ClassesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Collapsable_Expandable_ClassesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
